---
- name: "Provision Image"
  hosts: default
  become: true
  pre_tasks:
  - name: Update apt-get repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    ssh_server_ports: ['22']
    ssh_allow_agent_forwarding: "false"
    ssh_allow_tcp_forwarding: "false"
    ssh_permit_tunnel: "false"
    use_proxy: "false"
    #ssh_listen_to: "['{{ ansible_default_ipv4.address }}']"
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  #  - dev-sec.ssh-hardening

