---
name: Packer

on:
  push:
    branches:
      - Dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRODUCT_VERSION: "latest"

jobs:
  packer-lint:

    runs-on: ubuntu-22.04
    name: packer-lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: packer init packer/

      - name: Run `packer fmt`
        id: fmt
        run: packer fmt -check packer/

      - name: Run `packer validate`
        id: validate
        run: packer validate -syntax-only packer/
